// @contract: Tabla reservations. reservations → clients? + users.
import { pgTable, serial, integer, varchar, numeric, text, timestamp } from 'drizzle-orm/pg-core'
import { reservationStatusEnum, vehicleTypeEnum } from './enums'
import { clients } from './clients.schema'
import { users } from './users.schema'
import { vehicles } from './vehicles.schema'

export const reservations = pgTable('reservations', {
  id: serial('id').primaryKey(),
  reservationNumber: varchar('reservation_number', { length: 20 }),
  date: timestamp('date').notNull().defaultNow(),
  clientId: integer('client_id').references(() => clients.id),
  vehicleId: integer('vehicle_id').references(() => vehicles.id, { onDelete: 'set null' }),
  clientName: varchar('client_name', { length: 100 }).notNull(),
  clientDni: varchar('client_dni', { length: 20 }),
  clientAddress: varchar('client_address', { length: 200 }),
  clientPhone: varchar('client_phone', { length: 30 }),
  clientEmail: varchar('client_email', { length: 100 }),
  clientBirthDate: varchar('client_birth_date', { length: 20 }),
  clientLocality: varchar('client_locality', { length: 100 }),
  clientZip: varchar('client_zip', { length: 10 }),
  clientProvince: varchar('client_province', { length: 50 }),
  clientOccupation: varchar('client_occupation', { length: 80 }),
  patentingName: varchar('patenting_name', { length: 200 }),
  spouseName: varchar('spouse_name', { length: 100 }),
  spouseDni: varchar('spouse_dni', { length: 20 }),
  vehicleType: vehicleTypeEnum('vehicle_type').notNull().default('moto'),
  brand: varchar('brand', { length: 50 }).notNull(),
  model: varchar('model', { length: 50 }),
  year: integer('year'),
  color: varchar('color', { length: 30 }),
  motorNumber: varchar('motor_number', { length: 80 }),
  chassisNumber: varchar('chassis_number', { length: 80 }),
  hullNumber: varchar('hull_number', { length: 80 }),
  requestedUnit: varchar('requested_unit', { length: 200 }),
  price: numeric('price', { precision: 12, scale: 2 }),
  patentingAmount: numeric('patenting_amount', { precision: 12, scale: 2 }),
  depositAmount: numeric('deposit_amount', { precision: 12, scale: 2 }),
  paymentType: varchar('payment_type', { length: 20 }),
  tradeInValue: numeric('trade_in_value', { precision: 12, scale: 2 }),
  tradeInBrand: varchar('trade_in_brand', { length: 50 }),
  tradeInModel: varchar('trade_in_model', { length: 50 }),
  tradeInDomain: varchar('trade_in_domain', { length: 30 }),
  tradeInPlate: varchar('trade_in_plate', { length: 30 }),
  financingBalance: numeric('financing_balance', { precision: 12, scale: 2 }),
  financingType: varchar('financing_type', { length: 20 }),
  financingMethod: varchar('financing_method', { length: 20 }),
  financingInstallments: integer('financing_installments'),
  notes: text('notes'),
  status: reservationStatusEnum('status').notNull().default('vigente'),
  userId: integer('user_id').references(() => users.id).notNull(),
  createdAt: timestamp('created_at').defaultNow().notNull(),
})
